services:
  db:
    image: postgres:15
    container_name: weather_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pipeline:
    build: .
    container_name: weather_pipeline
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ~/.cache/kagglehub:/root/.cache/kagglehub
    environment:
      DATABASE_URL: postgres://user:password@db:5432/weather
    command: python src/ingest.py

volumes:
  postgres_data: